ktor:
  application:
    modules:
      - space.zghoba.ApplicationKt.module
  deployment:
    port: 8080

security:
  jwt:
    secret: $PPG_JWT_SECRET
    issuer: "/v1/token"
    audience: "/v1"
    realm: "Access to the API"
    lifetime-ms: 900000  # 15 min
  sessions:
    lifetime-ms: 900000  # 15 min
  hashing:
    pepper: $PPG_PEPPER
    algorithm: "SHA-512"
    salt-min-length: 32
    salt-max-length: 48

database:
  protocol: "jdbc:postgresql"
  host-with-path: $PPG_PROD_DB_HOST_WITH_PATH
  user: $PPG_PROD_DB_USER
  password: $PPG_PROD_DB_PASSWORD
  migrations-dir-path: "./migrations"