ktor:
  application:
    modules:
      - space.zghoba.ApplicationKt.module
  deployment:
    port: 8080

security:
  jwt:
    secret: $JWT_SECRET
    issuer: "/v1/token"
    audience: "/v1"
    realm: "Access to the API"
    lifetime-ms: 900000  # 15 min
  sessions:
    lifetime-ms: 900000  # 15 min
  hashing:
    pepper: $PEPPER
    algorithm: "SHA-512"
    salt-min-length: 32
    salt-max-length: 48

database:
  driver: "jdbc:postgresql"
  host: $DB_HOST
  port: $DB_PORT
  name: $DB_NAME
  user: $DB_USER
  password: $DB_PASSWORD
  migrations-dir-path: "./migrations"