name: Run unit and integration tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the current repository
        uses: actions/checkout@v5

      - name: Build and run tests
        run: |
          docker compose -f ./compose/docker-compose.test.yaml up \
            --build \
            --abort-on-container-exit \
            --exit-code-from papagei-test-backend
            
      - name: Cleanup
        if: always()
        run: docker compose -f ./compose/docker-compose.test.yaml down -v