name: Run unit and integration tests

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_ACCESS_TOKEN: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
  DOCKERHUB_REPOSITORY: ${{ secrets.DOCKERHUB_REPOSITORY }}
  TESTING_OUTPUT_FILE: "./.koverPrintCoverage-output.txt"
  COVERAGE_EXTRACTOR: ./.github/workflows/utils/extract-coverage-percent.sh
  COVERAGE_VALUE_FILE: "./.coverage-numeric-value.txt"
  MINIMAL_CODE_COVERAGE_PERCENTAGE: 80

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      # START A TEST INSTANCE OF THE DATABASE
      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Pull the database image
        run: docker pull $DOCKERHUB_USERNAME/$DOCKERHUB_REPOSITORY:latest

      - name: Run a container based on the image
        run: |
          docker run -d \
          --name papagei-test-db \
          -p 9002:5432 \
          -e POSTGRES_DB=${{ secrets.POSTGRES_DB }} \
          -e POSTGRES_USER=${{ secrets.POSTGRES_USER }} \
          -e POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} \
          $DOCKERHUB_USERNAME/$DOCKERHUB_REPOSITORY

      # RUN UNIT AND INTEGRATION TESTS
      - name: Checkout the current repository
        uses: actions/checkout@v5

      - name: Set up Amazon Corretto 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "corretto"
          cache: "gradle"

      - name: Run unit and integration tests
        id: tests
        env:
          PPG_TEST_DB_HOST_WITH_PATH: ${{ secrets.PPG_TEST_DB_HOST_WITH_PATH }}
          PPG_TEST_DB_USER: ${{ secrets.PPG_TEST_DB_USER }}
          PPG_TEST_DB_PASSWORD: ${{ secrets.PPG_TEST_DB_PASSWORD }}
        run: |
          chmod u+x ./gradlew
          ./gradlew koverPrintCoverage --quiet >> ./$TESTING_OUTPUT_FILE

      - name: Check the coverage percent
        run: |
          chmod u+x ./$COVERAGE_EXTRACTOR
          COVERAGE_PERCENTAGE=$(./$COVERAGE_EXTRACTOR ./$TESTING_OUTPUT_FILE)
          
          echo "The coverage percentage is $COVERAGE_PERCENTAGE%"
          if (( $(echo "$COVERAGE_PERCENT > $MINIMAL_CODE_COVERAGE_PERCENTAGE" | bc -l) )); then
            echo "Success. The coverage percentage is greater than $MINIMAL_CODE_COVERAGE_PERCENTAGE."
          else
            echo "Error. The coverage percentage is less than or equal to $MINIMAL_CODE_COVERAGE_PERCENTAGE."
          fi